sudo: required
services:
- docker
language: python
python:
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- pytest --cov=. -vv
notifications:
  email: false
deploy:
  provider: pypi
  user: stevepentland
  password:
    secure: iZ9D280Ob7OOj1kJ9tMSEPR+nPKc2j39IMy4KfU+YdpsP4ww60bdX/H+IucVex/TlyCPG6lEVLXHJp18CZCX7NShLCwZ800NoFZpVOyuqowYYKm7WxqSAl0nqYLbVNfF8Y5TSCkex3j1lw+aSPtsoQfsRb364TsbPC6A7VGuDXIsYhmAbwMQWEunQeNDWvgfHf2hvUkLUBA3GvR7spVvW/aw+x/oln94nn5ngdSryNpDvSsZnV0KqmIAsdA+Q9vEa4vKoSJ4BXi7X4152zwGOKG/yCOuQ1vJj9G6W6/nRNnrqlTeuUOi4Z5J8fTLp4o61EMM5QL72uBKdg7X3z/+j2ePMhAkzZlgMlRFaOjDm+DD+sFwG3YVW6K3scJIPwQXCofTNYII7fHbEvYFeDGMzxIzx//8XnXBmZUkQKAJkcQIZJZaxgPqxLUqQhHTZi1wQNDUo1vYpgB+UH5If7jr/4cQO1ACpp1wXA+K3115hT9GUztjHibu6HmQmC6ZP8ZMXw8WWEOASrqA81f0qrlXM45IWXEg8K+V4EhwAR5+g9M/V36xa1jwF+C7+cALfIsuIeNn63hAJjGMqgSgjMHODiijEFlyO2zK/2Sw3j7LlgMhxnsYAaaxRZz5psEgWNc5f+/lQChxPD+WlJjcbF/IU0UoVFe7qcHGx91gkYZ/MyU=
  on:
    tags: true
