sudo: 'required'
services:
  - 'docker'
language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=. -vv
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker build -t $IMAGE_REPO/$IMAGE_NAME .;
      docker tag $IMAGE_REPO/$IMAGE_NAME:latest $IMAGE_REPO/$IMAGE_NAME:$(git rev-parse HEAD)
      docker tag $IMAGE_REPO/$IMAGE_NAME:latest $IMAGE_REPO/$IMAGE_NAME:$(git rev-parse --short HEAD)
      docker tag $IMAGE_REPO/$IMAGE_NAME:latest $IMAGE_REPO/$IMAGE_NAME:$(date --iso-8601).$(git rev-parse --short HEAD)
      docker push $IMAGE_REPO/$IMAGE_NAME ;
    fi