sudo: required
services:
- docker
language: python
python:
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- pytest --cov=. -vv
notifications:
  email: false
deploy:
  provider: pypi
  user: stevepentland
  password:
    secure: GZECeifVaF9cEinwMHoufwfF07q1Mk3y8txdF2gbDhlZh3xZrA/u6MIgwBQC4d8Ut81rufBb7bWMTZsnTqNJQc9pA9CN2/ULaPOeryRfVcuY4EoKcCAuLPCSIi7ag8iga+5ubdiAHjmBU7ZT80FlOlSFENj2sEKhg2JrKcH3haja83vcosxu+9onY87l0UeGnFDPu+pyEEScb6yb203mC3nVbrKGDwhb/fWr94tydQSb7bPpd1DvGRyMtFAZUPEVTEnRKDDyDJksPbhLrb9qHMU0jIh4H4wVtGKzPpU+kAqGe0J8sNl1/+rmNe75gQ6fQM5zAgP32RZp+CU/9kZUJo/MH/BAUwIAIWewmhx5w4YpVNdb1UyH2nLDbWVaBNt9Noley7OwCgfXCQF9KmqFOdksUyYws3YL06W+qxUZrEIdLSWh7QCyYYEHJvW2qTCO415St9+bicWEiWLh/0wzUaq7SBz238JPl8NrniMgdE6yLLr9sxwvTz20nCmgwmlY1GOnIX6Y9p011xaQH7KQnG6M57EQ+WHZZWsTdzb7/PPoM3MXTF9Xarsy3wvMeqdNm1/b0Ct+mkCplg1RrsAkikwWgG6W6YsZUM39TskyNeBlz33gvQlFWOXhjGxSWxjWxUKJD/P5b3f8uHAzQf21GR+xJoFI7cp73tdA8G8T3Tc=
  on:
    tags: true
