# Copy this example file, removing .example from the name
# and you have your stack! Just change to the image name
# you are using and go
# Copy this example file, changing any values that you need
# for your particular setup and you're good to go
version: '3.5'
services:
  swarmer:
    image: 'stevepentland/swarmer:latest'
    depends_on:
      - redis
    networks:
      - swarmer-net
    environment:
      - REDIS_TARGET=redis
      - REDIS_PORT=6379
      - RUNNER_HOST_NAME=swarmer
      - RUNNER_PORT=8500
      - RUNNER_NETWORK=swarmer-net
    ports:
      - "8500:8500"
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: 'redis:5'
    networks:
      - swarmer-net
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - redis-data:/data
volumes:
  redis-data:
networks:
  swarmer-net:
    name: swarmer-net
    driver: overlay
